---
- hosts: mcp
  vars:
    http_port: 80
    max_clients: 200
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
  - name: ensure apache is at the latest version
    apt: name=apache2 state=latest
  - name: ensure apache is running (and enable it at boot)
    service: name=apache2 state=started enabled=yes
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
